<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

/**
 * Generated by srag\PluginGenerator v0.13.7
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Core 1 <support-core1@studer-raimann.ch>
 */

require_once __DIR__ . "/vendor/srag/dic/src/PHPVersionChecker.php";

$id = "srfp";
$version = "1.0.0";
$ilias_min_version = "6.0";
$ilias_max_version = "6.999";
$responsible = "studer + raimann ag - Team Core 1";
$responsible_mail = "support-core1@studer-raimann.ch";
