<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

namespace srag\Plugins\SrFilePatcher\Config;

use srag\Plugins\SrFilePatcher\Utils\SrFilePatcherTrait;
use ilSrFilePatcherPlugin;
use ilRadioGroupInputGUI;
use ilRadioOption;
use srag\ActiveRecordConfig\SrFilePatcher\ActiveRecordConfigFormGUI;

/**
 * Class ConfigFormGUI
 *
 * Generated by srag\PluginGenerator v0.13.7
 *
 * @package srag\Plugins\SrFilePatcher\Config
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Core 1 <support-core1@studer-raimann.ch>
 */
class ConfigFormGUI extends ActiveRecordConfigFormGUI
{

    use SrFilePatcherTrait;
    const PLUGIN_CLASS_NAME = ilSrFilePatcherPlugin::class;
    const CONFIG_CLASS_NAME = Config::class;


    /**
     * @inheritdoc
     */
    protected function initFields()/*: void*/
    {
        $this->fields = [
            Config::KEY_PATCHING_MODE => [
                self::PROPERTY_CLASS    => ilRadioGroupInputGUI::class,
                self::PROPERTY_REQUIRED => true,
                self::PROPERTY_SUBITEMS => [
                    Config::KEY_MODE_SINGLE_FILE => [
                        self::PROPERTY_CLASS => ilRadioOption::class
                    ],
                    Config::KEY_MODE_ALL_FILES => [
                        self::PROPERTY_CLASS => ilRadioOption::class
                    ]
                ],
                "setInfo" => self::txt("info_patching_mode")
            ]
        ];
    }
}
