<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

namespace srag\Plugins\SrFilePatcher\Config;

use srag\Plugins\SrFilePatcher\Utils\SrFilePatcherTrait;
use ilSrFilePatcherPlugin;
use srag\ActiveRecordConfig\SrFilePatcher\ActiveRecordConfig;

/**
 * Class Config
 *
 * Generated by srag\PluginGenerator v0.13.7
 *
 * @package srag\Plugins\SrFilePatcher\Config
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Core 1 <support-core1@studer-raimann.ch>
 */
class Config extends ActiveRecordConfig
{

    use SrFilePatcherTrait;
    const TABLE_NAME = "srfp_config";
    const PLUGIN_CLASS_NAME = ilSrFilePatcherPlugin::class;
    const KEY_SOME = "some";
    /**
     * @var array
     */
    protected static $fields
        = [
            self::KEY_SOME => self::TYPE_STRING
        ];
    // TODO: Implement Config
}
